WebsitePanel/Sources/WebsitePanel.WebDavPortal/Models/FileSystem/DeleteFilesModel.cs
using System.Collections.Generic;
using WebsitePanel.WebDavPortal.Models.Common;

namespace WebsitePanel.WebDavPortal.Models.FileSystem
{
    public class DeleteFilesModel : AjaxModel
    {
        public DeleteFilesModel()
        {
            DeletedFiles = new List<string>();
        }

        public List<string> DeletedFiles { get; set; }
    }
}

WebsitePanel/Sources/WebsitePanel.WebDavPortal/Models/FileSystem/ResourceTableItemModel.cs
using System;
using WebsitePanel.WebDav.Core.Client;
using WebsitePanel.WebDavPortal.Models.Common.DataTable;

namespace WebsitePanel.WebDavPortal.Models.FileSystem
{
    public class ResourceTableItemModel : JqueryDataTableBaseEntity
    {
        public string DisplayName { get; set; }
        public string Url { get; set; }
        public Uri Href { get; set; }
        public bool IsTargetBlank { get; set; }
        public bool IsFolder { get; set; }
        public long Size { get; set; }
        public bool IsRoot { get; set; }
        public long Quota { get; set; }
        public string Type { get; set; }
        public DateTime LastModified { get; set; }
        public string LastModifiedFormated { get; set; }
        public string IconHref { get; set; }
        public string FolderUrlAbsoluteString { get; set; }
        public string FolderUrlLocalString { get; set; }
        public string FolderName { get; set; }
        public string Summary { get; set; }

        public override dynamic this[int index]
        {
            get
            {
                switch (index)
                {
                    case 1 :
                    {
                        return Size;
                    }
                    case 2:
                    {
                        return LastModified;
                    }
                    case 3:
                    {
                        return Type;
                    }
                    default:
                    {
                        return DisplayName;
                    }
                }
            }
        }
    }
}

WebsitePanel/Sources/WebsitePanel.WebDavPortal/Models/FileSystem/UploadFileResult.cs
using System;

namespace WebsitePanel.WebDavPortal.Models.FileSystem
{
    public class UploadFileResult
    {
        private string _error;

        public string error
        {
            get { return _error; }
            set
            {
                if (!String.IsNullOrEmpty(value))
                {
                    _error = value;
                    deleteUrl = String.Empty;
                    thumbnailUrl = String.Empty;
                    url = String.Empty;
                }
            }
        }

        public string name { get; set; }

        public int size { get; set; }
        public string type { get; set; }
        public string url { get; set; }
        public string deleteUrl { get; set; }
        public string thumbnailUrl { get; set; }
        public string deleteType { get; set; }


        public string FullPath { get; set; }
        public string SavedFileName { get; set; }

        public string Title { get; set; }
    }
}

WebsitePanel/Sources/WebsitePanel.WebDavPortal/Controllers/FileSystemController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Net.Mime;
using System.Security.Policy;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using AutoMapper;
using log4net;
using WebsitePanel.WebDav.Core;
using WebsitePanel.WebDav.Core.Client;
using WebsitePanel.WebDav.Core.Config;
using WebsitePanel.WebDav.Core.Entities.Account.Enums;
using WebsitePanel.WebDav.Core.Exceptions;
using WebsitePanel.WebDav.Core.Extensions;
using WebsitePanel.WebDav.Core.Interfaces.Managers;
using WebsitePanel.WebDav.Core.Interfaces.Managers.Users;
using WebsitePanel.WebDav.Core.Interfaces.Security;
using WebsitePanel.WebDav.Core.Security.Authorization.Enums;
using WebsitePanel.WebDav.Core.Security.Cryptography;
using WebsitePanel.WebDav.Core.Wsp.Framework;
using WebsitePanel.WebDavPortal.CustomAttributes;
using WebsitePanel.WebDavPortal.Extensions;
using WebsitePanel.WebDavPortal.FileOperations;
using WebsitePanel.WebDavPortal.Helpers;
using WebsitePanel.WebDavPortal.ModelBinders.DataTables;
using WebsitePanel.WebDavPortal.Models;
using System.Net;
using WebsitePanel.WebDavPortal.Models.Common;
using WebsitePanel.WebDavPortal.Models.Common.DataTable;
using WebsitePanel.WebDavPortal.Models.Common.Enums;
using WebsitePanel.WebDavPortal.Models.FileSystem;
using WebsitePanel.WebDavPortal.UI;
using WebsitePanel.WebDavPortal.UI.Routes;
using WebsitePanel.WebDav.Core.Extensions;

namespace WebsitePanel.WebDavPortal.Controllers

{
    [ValidateInput(false)]
    [LdapAuthorization]
    public class FileSystemController : BaseController
    {
        private readonly ICryptography _cryptography;
        private readonly IWebDavManager _webdavManager;
        private readonly IAuthenticationService _authenticationService;
        private readonly IAccessTokenManager _tokenManager;
        private readonly IWebDavAuthorizationService _webDavAuthorizationService;
        private readonly IUserSettingsManager _userSettingsManager;
        private readonly FileOpenerManager _openerManager;
        private readonly ILog Log;

        public FileSystemController(ICryptography cryptography, IWebDavManager webdavManager, IAuthenticationService authenticationService, IAccessTokenManager tokenManager, IWebDavAuthorizationService webDavAuthorizationService, FileOpenerManager openerManager, IUserSettingsManager userSettingsManager)
        {
            _cryptography = cryptography;
            _webdavManager = webdavManager;
            _authenticationService = authenticationService;
            _tokenManager = tokenManager;
            _webDavAuthorizationService = webDavAuthorizationService;
            _userSettingsManager = userSettingsManager;

            Log = LogManager.GetLogger(this.GetType());
            _openerManager = new FileOpenerManager();
        }

        [HttpGet]
        public ActionResult ChangeViewType(FolderViewTypes viewType, string org, string pathPart = "")
        {
            _userSettingsManager.ChangeWebDavViewType(WspContext.User.AccountId, viewType);

            return RedirectToRoute(FileSystemRouteNames.ShowContentPath, new  { org, pathPart });
        }

        public ActionResult ShowContent(string org, string pathPart = "", string searchValue = "")
        {
            if (org != WspContext.User.OrganizationId)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NoContent);
            }

            if (_webdavManager.IsFile(pathPart))
            {
                var resource = _webdavManager.GetResource(pathPart);

                var mimeType = _openerManager.GetMimeType(Path.GetExtension(pathPart));

                return new FileStreamResult(resource.GetReadStream(), mimeType);
            }

            try
            {
                var model = new ModelForWebDav
                {
                    UrlSuffix = pathPart, 
                    Permissions =_webDavAuthorizationService.GetPermissions(WspContext.User, pathPart),
                    UserSettings = _userSettingsManager.GetUserSettings(WspContext.User.AccountId),
                    SearchValue = searchValue
                };

                if (Request.Browser.IsMobileDevice)
                {
                    model.UserSettings.WebDavViewType = FolderViewTypes.BigIcons;
                }

                return View(model);
            }
            catch (UnauthorizedException e)
            {
                throw new HttpException(404, "Not Found");
            }
        }

        [ChildActionOnly]
        public ActionResult ContentList(string org, ModelForWebDav model, string pathPart = "")
        {
            try
            {
                if (Request.Browser.IsMobileDevice == false && model.UserSettings.WebDavViewType == FolderViewTypes.Table)
                {
                    return PartialView("_ShowContentTable", model);
                }

                IEnumerable<IHierarchyItem> children;

                if (string.IsNullOrEmpty(model.SearchValue))
                {
                    children = _webdavManager.OpenFolder(pathPart);
                }
                else
                {
                    children = _webdavManager.SearchFiles(WspContext.User.ItemId, pathPart, model.SearchValue, WspContext.User.Login, true);
                }

                model.Items = children.Take(WebDavAppConfigManager.Instance.ElementsRendering.DefaultCount);

                return PartialView("_ShowContentBigIcons", model);
            }
            catch (UnauthorizedException e)
            {
                throw new HttpException(404, "Not Found");
            }
        }

        [HttpGet]
        public ActionResult GetContentDetails(string org, string pathPart, [ModelBinder(typeof (JqueryDataTableModelBinder))] JqueryDataTableRequest dtRequest)
        {
            IEnumerable<WebDavResource> folderItems;

            if (string.IsNullOrEmpty(dtRequest.Search.Value) == false)
            {
                folderItems = _webdavManager.SearchFiles(WspContext.User.ItemId, pathPart, dtRequest.Search.Value, WspContext.User.Login, true).Cast<WebDavResource>();
            }
            else
            {
                folderItems = _webdavManager.OpenFolder(pathPart).Cast<WebDavResource>();
            }

            var tableItems = Mapper.Map<IEnumerable<WebDavResource>, IEnumerable<ResourceTableItemModel>>(folderItems).ToList();

            FillContentModel(tableItems, org);

            var orders = dtRequest.Orders.ToList();
            orders.Insert(0, new JqueryDataTableOrder{Column = 3, Ascending = false});

            dtRequest.Orders = orders;

            var dataTableResponse = DataTableHelper.ProcessRequest(tableItems, dtRequest);

            return Json(dataTableResponse, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult ShowAdditionalContent(string path = "", int resourseRenderCount = 0)
        {
            path = path.Replace(WspContext.User.OrganizationId, "").Trim('/');

            IEnumerable<IHierarchyItem> children = _webdavManager.OpenFolder(path);

            var result = children.Skip(resourseRenderCount).Take(WebDavAppConfigManager.Instance.ElementsRendering.AddElementsCount);

            return PartialView("_ResourseCollectionPartial", result);
        }

        public ActionResult SearchFiles(string org, string pathPart, string searchValue)
        {
            if (string.IsNullOrEmpty(searchValue))
            {
                return RedirectToRoute(FileSystemRouteNames.ShowContentPath);
            }

            var model = new ModelForWebDav
            {
                UrlSuffix = pathPart,
                Permissions = _webDavAuthorizationService.GetPermissions(WspContext.User, pathPart),
                UserSettings = _userSettingsManager.GetUserSettings(WspContext.User.AccountId),
                SearchValue = searchValue
            };

            return View("ShowContentSearchResultTable", model);
        }

        [HttpGet]
        public ActionResult DownloadFile(string org, string pathPart)
        {
            if (org != WspContext.User.OrganizationId)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NoContent);
            }

            string fileName = pathPart.Split('/').Last();

            if (_webdavManager.IsFile(pathPart) == false)
            {
                throw new Exception(Resources.UI.NotAFile);
            }

            var fileBytes = _webdavManager.GetFileBytes(pathPart);

            return File(fileBytes, MediaTypeNames.Application.Octet, fileName);
        }

        [HttpGet]
        public ActionResult UploadFiles(string org, string pathPart)
        {
            var model = new ModelForWebDav
            {
                UrlSuffix = pathPart
            };

            return View(model);
        }

        [HttpPost]
        [ActionName("UploadFiles")]
        public ActionResult UploadFilePost(string org, string pathPart)
        {
            var uploadResults = new List<UploadFileResult>();

            foreach (string file in Request.Files)
            {
                var hpf = Request.Files[file] as HttpPostedFileBase;

                if (hpf == null || hpf.ContentLength == 0)
                {
                    continue;
                }

                _webdavManager.UploadFile(pathPart, hpf);

                uploadResults.Add(new UploadFileResult()
                {
                    name = hpf.FileName,
                    size = hpf.ContentLength,
                    type = hpf.ContentType
                });
            }


WebsitePanel/Sources/WebsitePanel.WebDavPortal/Views/FileSystem/ShowContent.cshtml
@using WebsitePanel.WebDav.Core
@using WebsitePanel.WebDav.Core.Client
@using Ninject
@using WebsitePanel.WebDav.Core.Config
@using WebsitePanel.WebDav.Core.Entities.Account.Enums
@using WebsitePanel.WebDav.Core.Interfaces.Managers
@using WebsitePanel.WebDav.Core.Security.Authorization.Enums
@using WebsitePanel.WebDavPortal.Resources
@using WebsitePanel.WebDavPortal.UI
@using WebsitePanel.WebDavPortal.UI.Routes

@model WebsitePanel.WebDavPortal.Models.ModelForWebDav


@if (Model != null && !string.IsNullOrEmpty(Model.Error))
{
    <span class="col-sm-offset-1" style="color: #A94442; font-weight: bold;">@Model.Error</span>
}
else
{
   @Html.Partial("_ShowContentTopMenu", Model)
    
   @Html.Action("ContentList", "FileSystem", new { model = Model });
}


@section scripts{
    
    <script>
        wsp.fileBrowser.setSettings({ 
            deletionUrl: "@Url.RouteUrl(FileSystemRouteNames.DeleteFiles)", 
            fileExistUrl: "@Url.RouteUrl(FileSystemRouteNames.ItemExist)",
            textItemExist: "@UI.ItemExist." });
    </script>

    @Scripts.Render("~/bundles/appScripts-webdav")
    
    @if (Model.UserSettings.WebDavViewType == FolderViewTypes.BigIcons)
    {
        @Scripts.Render("~/bundles/bigIconsScripts")

        <script>
            $(document).ready(function () {
                @if (string.IsNullOrEmpty(Model.SearchValue))
                {
                    @:wsp.fileBrowser.initBigIcons('#resourcesDiv', '@Url.RouteUrl(FileSystemRouteNames.ShowAdditionalContent)');
                }
                recalculateResourseHeight();
            });
        </script>
    }
    else
    {
        <script>
            $(document).ready(function () {
                wsp.fileBrowser.initDataTable('#webdav-items-table', '@Url.RouteUrl(FileSystemRouteNames.ShowContentDetails)');
            });
        </script>
    }
}

@section popups{
    <div id="createNewItemDialog" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="modal-process-dialog-title" data-backdrop="static" data-keyboard="false" aria-hidden="true" style="display: none;">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                    <h4 class="modal-title" id="create-dalog-label" data-title="@UI.Create">@UI.Create</h4>
                </div>

                <div class="modal-body">
                    <form id="filenameForm">
                        <div class="form-group has-feedback">
                            <label for="filename">@UI.FileName</label>
                            <input type="text" class="form-control" id="filename" name="filename" autofocus required placeholder="@UI.EnterFileName">
                            <span class="glyphicon glyphicon-refresh glyphicon-spin form-control-feedback small-processing" aria-hidden="true"></span>
                            <span id="inputProcessingStatus" class="sr-only">(processing)</span>
                        </div>
                    </form>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">@UI.Cancel</button>
                    <a href="@Url.RouteUrl(FileSystemRouteNames.NewWebDavItem)" data-href="@Url.RouteUrl(FileSystemRouteNames.NewWebDavItem)" id="create-button" class="btn btn-success danger">@UI.Create</a>
                </div>
            </div>
        </div>
    </div>
}

WebsitePanel/Sources/WebsitePanel.WebDavPortal/Views/FileSystem/ShowContentSearchResultTable.cshtml
@using WebsitePanel.WebDavPortal.Resources
@using WebsitePanel.WebDavPortal.UI.Routes
@model WebsitePanel.WebDavPortal.Models.ModelForWebDav
           

@Html.Partial("_ShowContentTopMenu", Model)

<div class="prevent-deselect container">
    <table id="search-items-table" class="display table table-striped table-bordered noselect" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>@UI.File</th>
                <th>@UI.Details</th>
            </tr>
        </thead>
    </table>
</div>

@section scripts
{
    <script>
        $(document).ready(function() {
            wsp.fileBrowser.setSettings({ deletionUrl: "@Url.RouteUrl(FileSystemRouteNames.DeleteFiles)" });
            wsp.fileBrowser.initSearchDataTable('#search-items-table', '@Url.RouteUrl(FileSystemRouteNames.ShowContentDetails)', '@Model.SearchValue');
        });
    </script>
    @Scripts.Render("~/bundles/appScripts-webdav")
}


WebsitePanel/Sources/WebsitePanel.WebDavPortal/Views/FileSystem/ShowOfficeDocument.cshtml
@using WebsitePanel.WebDavPortal.UI.Routes
@model WebsitePanel.WebDavPortal.Models.OfficeOnlineModel
@{
  Layout = null;
}

<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width" />
        <title>@Html.Raw(Model.FileName)</title>
        @if (Request.Browser.IsMobileDevice)
        {
            @Styles.Render("~/Content/css")
        }
    </head>
    <body>
        @if (Request.Browser.IsMobileDevice)
        {
            <div class="navbar navbar-inverse navbar-fixed-top">
                <div class="container top-container">
                    <div class="navbar-header">
                        <a class="back-button" href="@Url.RouteUrl(FileSystemRouteNames.ShowContentPath, new {pathPart = Model.Backurl})">
                            <i class="glyphicon glyphicon-circle-arrow-left"></i>
                        </a>
                    </div>
                </div>
            </div>
        }
        <iframe src="@Model.Url" width="100%" height="100%" frameborder='0' style="position: absolute;top: 0;left: 0;bottom: 0;right: 0; @(Request.Browser.IsMobileDevice ? "margin-top: 50px;" : "")">
            This is an embedded
            <a target='_blank' href='http://office.com'>Microsoft Office</a> document, powered by
            <a target='_blank' href='http://office.com/webapps'>Office Web Apps</a>.
        </iframe>
    </body>
</html>

WebsitePanel/Sources/WebsitePanel.WebDavPortal/Views/FileSystem/UploadFiles.cshtml
@using WebsitePanel.WebDavPortal.Resources
@using WebsitePanel.WebDavPortal.UI.Routes
@model WebsitePanel.WebDavPortal.Models.ModelForWebDav
           
<div class="file-upload-menu">
    @Html.Partial("_ShowContentTopMenu", Model)
</div>


@using(Html.BeginRouteForm(FileSystemRouteNames.UploadFile, FormMethod.Post, new { id="file-upload-form", enctype="multipart/form-data"}))
{
    
<div class="row fileupload-buttonbar">
    <div class="col-lg-12">
        <div id="drag-and-drop-area" class="drag-and-drop-area">
            <span class="info-block">
                <i class="glyphicon glyphicon-upload upload-block-icon"></i>
                <span class="upload-block-text">
                    @UI.SelectFilesToUpload
                </span>
                <span class="upload-block-description">
                    @UI.OrDragAndDropFilesHere
                </span>
            </span>
            <div class="upload-block">
                <input id="file-input" type="file" tabindex="0" multiple>
            </div>
        </div>
    </div>
    <!-- The global file processing state -->
    <span class="fileupload-process"></span>
    <!-- The global progress state -->
    <div class="col-lg-12 fileupload-progress fileupload-global-process fade">
        <!-- The global progress bar -->
        <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
            <div class="progress-bar progress-bar-success" style="width: 0%;"></div>
        </div>
        <!-- The extended global progress state -->
        <div>
            <div class="progress-extended">&nbsp;</div>
            <div class="cancel-all">
                <button type="reset" class="btn btn-default cancel">
                    <i class="glyphicon glyphicon-ban-circle"></i>
                    <span>@UI.CancelAll</span>
                </button>
            </div>
        </div>
    </div>
</div>
<!-- The table listing the files available for upload/download -->
<table role="presentation" class="table table-striped"><tbody class="files"></tbody></table>
}

<!-- The template to display files available for upload -->
<script id="template-upload" type="text/x-tmpl">
    {% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-upload fade">
        <td class="column-name">
            <p class="name">{%=file.name%}</p>
            <strong class="error text-danger"></strong>
        </td>
        <td class="column-progress">
            <div>
                <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0">
                    <div class="progress-bar progress-bar-success" style="width:0%;">
                    </div>
                </div>
                <p class="size"></p>
            </div>
        </td>
        <td class="column-actions">
            <div class="file-actions">
                {% if (!i && !o.options.autoUpload) { %}
                <span class="start" title="@UI.Upload" disabled>
                    <i class="glyphicon glyphicon-upload"></i>
                </span>
                {% } %}
                {% if (!i) { %}
                <span class="cancel" title="@UI.Cancel">
                    <i class="glyphicon glyphicon-ban-circle"></i>
                </span>
                {% } %}
            </div>
        </td>
    </tr>
    {% } %}
</script>
<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
    {% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
        <td class="column-name">
            <p class="name">
                {% if (file.url) { %}
                <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" {%=file.thumbnailUrl?'data-gallery':''%}>{%=file.name%}</a>
                {% } else { %}
                <span>{%=file.name%}</span>
                {% } %}
            </p>
            {% if (file.error) { %}
            <div><span class="label label-danger">@UI.Error</span> {%=file.error%}</div>
            {% } %}
        </td>
        <td class="column-progress">
            <span class="size">{%=o.formatFileSize(file.size)%}</span>
        </td>
        <td class="column-actions">
            <div class="file-actions">
                <span class="cancel" title="@UI.Close">
                    <i class="glyphicon glyphicon-remove"></i>
                </span>
            </div>
        </td>
    </tr>
    {% } %}
</script>


@section scripts{
    @Scripts.Render("~/bundles/file-upload")

<script type="text/javascript">
    wsp.fileBrowser.initFileUpload('#file-upload-form', '@Url.RouteUrl(FileSystemRouteNames.UploadFile)');
</script>
}

WebsitePanel/Sources/WebsitePanel.WebDavPortal/Views/FileSystem/_ResourseCollectionPartial.cshtml
@model IEnumerable<WebsitePanel.WebDav.Core.Client.IHierarchyItem>

@foreach (var element in Model)
{
    @Html.Partial("_ResoursePartial", element)
}

WebsitePanel/Sources/WebsitePanel.WebDavPortal/Views/FileSystem/_ResoursePartial.cshtml
@using System.Net.Mime
@using WebsitePanel.WebDav.Core
@using WebsitePanel.WebDav.Core.Client
@using WebsitePanel.WebDav.Core.Config
@using WebsitePanel.WebDavPortal.FileOperations
@using Ninject;
@using WebsitePanel.WebDavPortal.Helpers
@using WebsitePanel.WebDavPortal.Resources
@using WebsitePanel.WebDavPortal.UI
@using WebsitePanel.WebDavPortal.UI.Routes
@model IHierarchyItem
  
@{
    string actualPath = Model.ItemType == ItemType.Folder ? "~/Content/Images/folder_100x100.png" : WebDavAppConfigManager.Instance.FileIcons[Path.GetExtension(Model.DisplayName.Trim('/'))];
    string name = Model.DisplayName.Trim('/');
    var _opener = new FileOpenerManager();
    var opener = _opener[Path.GetExtension(Model.DisplayName)];
    bool isTargetBlank;
    string href = "/";
    switch (opener)
    {
        case FileOpenerType.OfficeOnline:
            isTargetBlank = !Request.Browser.IsMobileDevice;
            var pathPart = Model.Href.AbsolutePath.Replace("/" + WspContext.User.OrganizationId, "").TrimStart('/'); 
            href = string.Concat(Url.RouteUrl(FileSystemRouteNames.EditOfficeOnline, new { org = WspContext.User.OrganizationId, pathPart = "" }), pathPart);
            break;
        default:
            isTargetBlank = false;
            href = Model.Href.LocalPath; 
            break;
    }

    var resource = Model as IResource;
    
    bool showStatistic = Model.ItemType == ItemType.Folder && Model.IsRootItem && resource != null;

    var contentTypeProperty = Model.Properties.FirstOrDefault(x => x.Name.Name == "getcontenttype");

    if (isTargetBlank == false && Model.ItemType != ItemType.Folder)
    {
        isTargetBlank = _opener.GetIsTargetBlank(Model) && !Request.Browser.IsMobileDevice;
    }

    int percent = 0;

    if (showStatistic)
    {
        percent = (int)(resource.AllocatedSpace != 0 ? 100 * resource.ContentLength / resource.AllocatedSpace : 0);    
    }
}

<div class="col-sm-2 element-container">
    <div class="element">
        <img class="icon-size" src="@Url.Content(actualPath)" />

        <a href="@href" @Html.Raw(isTargetBlank ? "target=\"_blank\"" : string.Empty) class="file-link @(Model.ItemType == ItemType.Folder ? "processing-dialog" : "")" title="@name">
            <p style="word-wrap: break-word;">@name</p>
        </a>

        @if (showStatistic)
        {
            <div class="progress web-dav-folder-progress">
                <div class="progress-bar" role="progressbar" aria-valuenow="@percent" aria-valuemin="0" aria-valuemax="100" style="width: @percent%;">
                    <p class="progress-text">@percent%</p>
                </div>
            </div>
            <p class="resource-subtext">@ViewDataHelper.BytesToSize(resource.ContentLength) / @ViewDataHelper.BytesToSize(resource.AllocatedSpace)</p>
        }

        <div class="selected-element-overlay">
        </div>
    </div>
</div>

WebsitePanel/Sources/WebsitePanel.WebDavPortal/Views/FileSystem/_ShowContentBigIcons.cshtml
@using WebsitePanel.WebDav.Core.Client
@using WebsitePanel.WebDavPortal.Resources
@using WebsitePanel.WebDavPortal.UI.Routes
@model WebsitePanel.WebDavPortal.Models.ModelForWebDav

<div class="container">


    <div class="row" id="resourcesDiv">
        @if (Model != null)
        {
            foreach (IHierarchyItem element in Model.Items)
            {
                @Html.Partial("_ResoursePartial", element)
            }
        }
    </div>
</div>

WebsitePanel/Sources/WebsitePanel.WebDavPortal/Views/FileSystem/_ShowContentTable.cshtml
@using WebsitePanel.WebDavPortal.Resources
@using WebsitePanel.WebDavPortal.UI.Routes

@model WebsitePanel.WebDavPortal.Models.ModelForWebDav

<div class="prevent-deselect container row">
    <table id="webdav-items-table" class="display table table-striped table-bordered noselect" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>@UI.Name</th>
                <th>@UI.Type</th>
                <th>@UI.Modified</th>
            </tr>
        </thead>
    </table>
</div>
